auth.py
# auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, logout_user, current_user, login_required
from werkzeug.security import check_password_hash, generate_password_hash
from models import User
from __init__ import db

auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        # Redirect to the dashboard based on whether the user is an admin or not
        return redirect(url_for('routes.admin_dashboard')) if current_user.is_admin else redirect(url_for('routes.user_dashboard'))
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        user = User.query.filter_by(email=email).first()
        if user and user.check_password(password):
            login_user(user)
            # Redirect to the dashboard based on whether the user is an admin or not
            return redirect(url_for('routes.admin_dashboard')) if user.is_admin else redirect(url_for('routes.user_dashboard'))
        flash('Invalid username or password')
    return render_template('Auth/user_login.html')  # Use a generic login template or separate ones if preferred


@auth_bp.route('/user_signup', methods=['GET', 'POST'])
def user_signup():
    if current_user.is_authenticated:
        return redirect(url_for('routes.user_dashboard'))
    if request.method == 'POST':
        # Extract form data
        first_name = request.form.get('firstname')
        last_name = request.form.get('lastname')
        email = request.form.get('email')
        password = request.form.get('password')
        password_confirm = request.form.get('password1')
        electricity_meter_number = request.form.get('electricity_meter_number')
        water_meter_number = request.form.get('water_meter_number')

        # Validate password match and email uniqueness
        if password != password_confirm:
            flash('Passwords must match.')
            return redirect(url_for('auth.user_signup'))
        
        if User.query.filter_by(email=email).first() is not None:
            flash('Email already in use.')
            return redirect(url_for('auth.user_signup'))

        # Create new user instance
        new_user = User(
            firstname=first_name, 
            lastname=last_name, 
            email=email, 
            electricity_meter_number=electricity_meter_number,
            water_meter_number=water_meter_number,
            is_admin=False
        )
        new_user.set_password(password)

        # Add new user to the database
        db.session.add(new_user)
        db.session.commit()

        flash('Account created successfully!')
        return redirect(url_for('auth.login'))
    
    return render_template('Auth/user_signup.html')

@auth_bp.route('/admin_signup', methods=['GET', 'POST'])
def admin_signup():
    if current_user.is_authenticated:
        return redirect(url_for('routes.user_dashboard'))
    if request.method == 'POST':
        # Extract form data
        first_name = request.form.get('firstname')
        last_name = request.form.get('lastname')
        email = request.form.get('email')
        password = request.form.get('password')
        password_confirm = request.form.get('password1')

        # Validate password match and email uniqueness
        if password != password_confirm:
            flash('Passwords must match.')
            return redirect(url_for('auth.user_signup'))
        
        if User.query.filter_by(email=email).first() is not None:
            flash('Email already in use.')
            return redirect(url_for('auth.user_signup'))

        # Create new user instance
        new_user = User(
            firstname=first_name, 
            lastname=last_name, 
            email=email, 
            is_admin=True
        )
        new_user.set_password(password)

        # Add new user to the database
        db.session.add(new_user)
        db.session.commit()

        flash('Account created successfully!')
        return redirect(url_for('auth.login'))
    
    return render_template('Auth/admin_signup.html')

@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('routes.index'))  # Adjust to your landing page route

routes.py
# routes.py
from flask import Blueprint, render_template,  redirect, url_for, request, flash, current_app
from flask_login import current_user, login_required
from models import User
from sqlalchemy import func
from datetime import datetime, timedelta
from models import EnergyUsage, Recommendations
import numpy as np
import matplotlib
matplotlib.use('Agg')  # Use this backend before importing pyplot
import matplotlib.pyplot as plt
from __init__ import db

routes_bp = Blueprint('routes', __name__)

@routes_bp.route('/')
def index():
    return render_template('index.html')

# User-specific routes
@routes_bp.route('/users/dashboard')
@login_required
def user_dashboard():
    if current_user.is_admin:
        return redirect(url_for('routes.admin_dashboard'))
    
    # Get the most recent recommendation
    most_recent_recommendation = Recommendations.query.filter_by(user_id=current_user.id).order_by(Recommendations.id.desc()).first()
    
    # Calculate average units used for water and electricity
    average_electricity = db.session.query(func.round(func.avg(EnergyUsage.units_used))).filter(
        EnergyUsage.user_id == current_user.id, 
        EnergyUsage.energy_type == 'electricity'
    ).scalar() or 0  # Default to 0 if no records are found

    average_water = db.session.query(func.round(func.avg(EnergyUsage.units_used))).filter(
        EnergyUsage.user_id == current_user.id, 
        EnergyUsage.energy_type == 'water'
    ).scalar() or 0  # Default to 0 if no records are found
    return render_template('Users/user_dashboard.html', most_recent_recommendation=most_recent_recommendation, average_electricity=average_electricity, average_water=average_water)

@routes_bp.route('/users/data_entry', methods=['GET', 'POST'])
@login_required
def data_entry():
    if current_user.is_admin:
        return redirect(url_for('routes.admin_dashboard'))

    if request.method == 'POST':
        # Get data from form
        energy_type = request.form.get('energyType')
        units_used = request.form.get('unitsUsed')
        date_recorded = request.form.get('date')

        new_usage = EnergyUsage(
            user_id=current_user.id,
            energy_type=energy_type,
            units_used=units_used,
            date_recorded=datetime.strptime(date_recorded, '%Y-%m-%d')
        )

        # Add to the session and commit
        db.session.add(new_usage)
        try:
            db.session.commit()
            flash('Energy usage recorded successfully!', 'success')
        except Exception as e:
            db.session.rollback()
            flash('An error occurred. Unable to record energy usage.', 'error')

        # Redirect to a new page or the same page to show a success message or to clear the form
        return redirect(url_for('routes.data_entry'))

    # GET request - just render the template
    return render_template('Users/data_entry.html')

from flask import request
from sqlalchemy import func
from datetime import datetime, timedelta

@routes_bp.route('/users/history')
@login_required
def history():
    if current_user.is_admin:
        return redirect(url_for('routes.admin_dashboard'))

    # Get the selected time period, aggregation, and energy type from the dropdown menus
    time_period = request.args.get('time_period', '7 days')  # Default to last 7 days
    energy_type = request.args.get('energy_type', 'electricity')  # Default to electricity
    
    # Adjust the query based on the selected time period and energy type
    if time_period == '7 days':
        start_date = datetime.now() - timedelta(days=7)
    elif time_period == '30 days':
        start_date = datetime.now() - timedelta(days=30)
    elif time_period == '3 months':
        start_date = datetime.now() - timedelta(days=90)  # Assuming 3 months = 90 days
    elif time_period == '6 months':
        start_date = datetime.now() - timedelta(days=180)  # Assuming 6 months = 180 days
    
    # Filter the records based on time period and energy type
    records = EnergyUsage.query.filter(EnergyUsage.user_id == current_user.id,
                                       EnergyUsage.energy_type == energy_type,
                                       EnergyUsage.date_recorded >= start_date).all()
    
    # Get the value of the aggregation parameter
    aggregation = request.args.get('aggregate', 'all')  # Default to all records
    
    if aggregation == 'aggregate':
        # Calculate the total units used and average units used
        total_units_used = sum(record.units_used for record in records)
        average_units_used = total_units_used / len(records) if records else 0
        records = None  # Reset records to None since we're showing aggregates
        show_aggregate = True
    else:
        total_units_used = None
        average_units_used = None
        show_aggregate = False
    
    return render_template('Users/history.html', records=records, time_period=time_period,
                           total_units_used=total_units_used, average_units_used=average_units_used,
                           aggregation=aggregation, show_aggregate=show_aggregate)

import os

@routes_bp.route('/users/power_usage')
@login_required
def power_usage():
    if current_user.is_admin:
        return redirect(url_for('routes.admin_dashboard'))

    energy_types = ['electricity', 'water', 'naturalgas', 'vehiclefuel']
    latest_graphs = {}

    for energy_type in energy_types:
        end_date = datetime.now()
        start_date = end_date - timedelta(weeks=10)
        energy_data = EnergyUsage.query.filter(
            EnergyUsage.user_id == current_user.id,
            EnergyUsage.energy_type == energy_type,
            EnergyUsage.date_recorded >= start_date,
            EnergyUsage.date_recorded <= end_date
        ).all()

        if not energy_data:
            latest_graphs[energy_type] = {'bar_graph_exists': False, 'line_graph_exists': False}
            continue

        weekly_dates = [(end_date - timedelta(weeks=i)).strftime('%Y-%m-%d') for i in range(10)]
        weekly_usage = [sum(data.units_used for data in energy_data if data.date_recorded.strftime('%Y-%m-%d') == date) for date in weekly_dates]
        all_time_dates = [(end_date - timedelta(days=i)).strftime('%Y-%m-%d') for i in range(21)]
        all_time_usage = [sum(data.units_used for data in energy_data if data.date_recorded.strftime('%Y-%m-%d') == date) for date in all_time_dates]

        timestamp = datetime.now().strftime('%Y%m%d%H%M%S')
        bar_graph_filename = f'{energy_type}_bar_graph_{timestamp}.png'
        line_graph_filename = f'{energy_type}_line_graph_{timestamp}.png'

        # Save bar graph
        bar_graph_path = os.path.join(current_app.root_path, 'static', 'Images', bar_graph_filename)
        plt.figure(figsize=(10, 6))
        plt.bar(weekly_dates, weekly_usage)
        plt.xlabel('Date')
        plt.ylabel('Energy Usage')
        plt.title(f'Weekly {energy_type.capitalize()} Usage')
        plt.xticks(rotation=45)
        plt.savefig(bar_graph_path, format='png')
        plt.close()

        # Save line graph
        line_graph_path = os.path.join(current_app.root_path, 'static', 'Images', line_graph_filename)
        plt.figure(figsize=(10, 6))
        plt.plot(all_time_dates, all_time_usage, marker='o')
        plt.xlabel('Date')
        plt.ylabel('Energy Usage')
        plt.title(f'All-Time {energy_type.capitalize()} Usage')
        plt.xticks(rotation=45)
        plt.savefig(line_graph_path, format='png')
        plt.close()

        # Store the latest file names
        latest_graphs[energy_type] = {
            'bar_graph_exists': True, 'bar_graph_filename': bar_graph_filename,
            'line_graph_exists': True, 'line_graph_filename': line_graph_filename
        }

    return render_template('Users/power_usage.html', latest_graphs=latest_graphs)

@routes_bp.route('/users/recommendations')
@login_required
def recommendations():
    if current_user.is_admin:
        return redirect(url_for('routes.admin_dashboard'))
    
    # Define energy types
    energy_types = ['electricity', 'water', 'naturalgas', 'vehiclefuel']
    
    end_date = datetime.now()
    start_date = end_date - timedelta(days=7)
    latest_recommendations = []

    for energy_type in energy_types:
        energy_data = EnergyUsage.query.filter(
            EnergyUsage.user_id == current_user.id,
            EnergyUsage.energy_type == energy_type,
            EnergyUsage.date_recorded >= start_date,
            EnergyUsage.date_recorded <= end_date
        ).order_by(EnergyUsage.date_recorded.desc()).all()

        if not energy_data:
            continue

        # Find the latest date for current energy type data
        latest_date = max(data.date_recorded for data in energy_data)

        usage_values = [data.units_used for data in energy_data if data.date_recorded == latest_date]
        first_quartile = np.percentile(usage_values, 25)
        third_quartile = np.percentile(usage_values, 75)
        max_usage = max(usage_values)

        for data in energy_data:
            if data.date_recorded == latest_date:
                if data.units_used < first_quartile:
                    recommendation = "Congratulations! Your energy usage is below average."
                elif data.units_used > third_quartile:
                    recommendation = "Consider reducing energy usage. Your usage is higher than usual."
                elif data.units_used == max_usage:
                    recommendation = "Warning! Your energy usage today is the highest recorded in the past week."
                else:
                    recommendation = "No specific recommendation for today. Continue to monitor energy usage."

                db_recommendation = Recommendations(user_id=current_user.id, recommendation=recommendation, date_recorded=data.date_recorded, energy_type=energy_type)
                db.session.add(db_recommendation)
                

templates/Users/data_entry.html
<!doctype html>
<html lang="en">
  <head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/dashboard.css') }}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body class="home">
        <div class="container-fluid display-table">
            <div class="row display-table-row">
                <div class="col-md-2 col-sm-1 hidden-xs display-table-cell v-align box" id="navigation">
                    <div class="logo">
                        <a href="{{ url_for('routes.index') }}"><img src="../static/Images/userIcon.png" class="hidden-xs hidden-sm">
                        </a>
                    </div>
                    <div class="navi">
                        <ul>
                            <li><a href="{{ url_for('routes.user_dashboard') }}"><i class="fa fa-home" aria-hidden="true"></i><span class="hidden-xs hidden-sm">User Dashboard</span></a></li>
                            <li><a href="{{ url_for('routes.power_usage') }}"><i class="fa fa-tasks" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Power Usage</span></a></li>
                            <li class="active"><a href="{{ url_for('routes.data_entry') }}"><i class="fa fa-bar-chart" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Record Data</span></a></li>
                            <li><a href="{{ url_for('routes.history') }}"><i class="fa fa-user" aria-hidden="true"></i><span class="hidden-xs hidden-sm">History Data</span></a></li>
                            <li><a href="{{ url_for('routes.recommendations') }}"><i class="fa fa-calendar" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Recommendations</span></a></li>
                            <li><a href="{{ url_for('routes.settings') }}"><i class="fa fa-cog" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Setting</span></a></li>
                        </ul>
                        
                    </div>
                </div>
                <div class="col-md-10 col-sm-11 display-table-cell v-align">
                    <!--<button type="button" class="slide-toggle">Slide Toggle</button> -->
                    <div class="row">
                        <header>
                            <div class="col-sm-7">
                                <nav class="navbar-default pull-left">
                                    <div class="navbar-header">
                                        <button type="button" class="navbar-toggle collapsed" data-toggle="offcanvas" data-target="#side-menu" aria-expanded="false">
                                            <span class="sr-only">Toggle navigation</span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                        </button>
                                    </div>
                                </nav>
                                
                            </div>
                            <div class="col-sm-12 text-right"> <!-- Adjusted class to 'text-right' -->
                                <div class="header-rightside">
                                    <ul class="list-inline header-top pull-right">
                                        <li class="hidden-xs"><a href="{{ url_for('routes.settings') }}" class="add-project" data-toggle="modal">Settings</a></li>
                                        <li><a href="#"><i class="fa fa-envelope" aria-hidden="true"></i></a></li>
                                        <li>
                                            <a href="#" class="icon-info">
                                                <i class="fa fa-bell" aria-hidden="true"></i>
                                                <span class="label label-primary">3</span>
                                            </a>
                                        </li>
                                        <li class="dropdown">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="../static/Images/userIcon.png" alt="user">
                                                <b class="caret"></b></a>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <div class="navbar-content">
                                                        <span>{{ current_user.firstname }} {{ current_user.lastname }}</span>
                                                        <p class="text-muted small">
                                                            {{ current_user.email }}
                                                        </p>
                                                        <div class="divider">
                                                        </div>
                                                        <a href="{{ url_for('auth.logout') }}" class="view btn-sm active">Log Out</a>
                                                    </div>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                    
                                </div>
                                
                            </div>
                        </header>
                    </div>
                    
                    <div class="user-dashboard">
                        <h1>Data Entry</h1>
                        <!-- Energy Usage Form -->
                        <div class="row">
                            <div class="col-md-12">
                                <h2>Energy Usage Entry</h2>
                                <form method="post" action="{{ url_for('routes.data_entry') }}">
                                    <div class="form-group">
                                        <label for="energyType">Energy Type</label>
                                        <select class="form-control" id="energyType" name="energyType">
                                            <option value="electricity">Electricity</option>
                                            <option value="water">Water</option>
                                            <option value="naturalgas">Natural Gas</option>
                                            <option value="vehiclefuel">Vehicle Fuel</option>
                                            <!-- Add more options for other energy types if needed -->
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label for="unitsUsed">Units Used</label>
                                        <input type="number" class="form-control" id="unitsUsed" name="unitsUsed">
                                    </div>
                                    <div class="form-group">
                                        <label for="date">Date</label>
                                        <input type="date" class="form-control" id="date" name="date">
                                    </div>
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </form>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
    
        </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/Users/power_usage.html
<!doctype html>
<html lang="en">
  <head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/dashboard.css') }}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body class="home">
        <div class="container-fluid display-table">
            <div class="row display-table-row">
                <div class="col-md-2 col-sm-1 hidden-xs display-table-cell v-align box" id="navigation">
                    <div class="logo">
                        <a href="{{ url_for('routes.index') }}"><img src="../static/Images/userIcon.png" class="hidden-xs hidden-sm">
                        </a>
                    </div>
                    <div class="navi">
                        <ul>
                            <li><a href="{{ url_for('routes.user_dashboard') }}"><i class="fa fa-home" aria-hidden="true"></i><span class="hidden-xs hidden-sm">User Dashboard</span></a></li>
                            <li class="active"><a href="{{ url_for('routes.power_usage') }}"><i class="fa fa-tasks" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Power Usage</span></a></li>
                            <li><a href="{{ url_for('routes.data_entry') }}"><i class="fa fa-bar-chart" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Record Data</span></a></li>
                            <li><a href="{{ url_for('routes.history') }}"><i class="fa fa-user" aria-hidden="true"></i><span class="hidden-xs hidden-sm">History Data</span></a></li>
                            <li><a href="{{ url_for('routes.recommendations') }}"><i class="fa fa-calendar" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Recommendations</span></a></li>
                            <li><a href="{{ url_for('routes.settings') }}"><i class="fa fa-cog" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Setting</span></a></li>
                        </ul>
                        
                    </div>
                </div>
                <div class="col-md-10 col-sm-11 display-table-cell v-align">
                    <!--<button type="button" class="slide-toggle">Slide Toggle</button> -->
                    <div class="row">
                        <header>
                            <div class="col-sm-7">
                                <nav class="navbar-default pull-left">
                                    <div class="navbar-header">
                                        <button type="button" class="navbar-toggle collapsed" data-toggle="offcanvas" data-target="#side-menu" aria-expanded="false">
                                            <span class="sr-only">Toggle navigation</span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                        </button>
                                    </div>
                                </nav>
                                
                            </div>
                            <div class="col-sm-12 text-right"> <!-- Adjusted class to 'text-right' -->
                                <div class="header-rightside">
                                    <ul class="list-inline header-top pull-right">
                                        <li class="hidden-xs"><a href="{{ url_for('routes.settings') }}" class="add-project" data-toggle="modal">Settings</a></li>
                                        <li><a href="#"><i class="fa fa-envelope" aria-hidden="true"></i></a></li>
                                        <li>
                                            <a href="#" class="icon-info">
                                                <i class="fa fa-bell" aria-hidden="true"></i>
                                                <span class="label label-primary">3</span>
                                            </a>
                                        </li>
                                        <li class="dropdown">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="../static/Images/userIcon.png" alt="user">
                                                <b class="caret"></b></a>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <div class="navbar-content">
                                                        <span>{{ current_user.firstname }} {{ current_user.lastname }}</span>
                                                        <p class="text-muted small">
                                                            {{ current_user.email }}
                                                        </p>
                                                        <div class="divider">
                                                        </div>
                                                        <a href="{{ url_for('auth.logout') }}" class="view btn-sm active">Log Out</a>
                                                    </div>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </header>
                    </div>
                    
                    <div class="user-dashboard" style="overflow-y: auto; max-height: 90vh;">
                        <h1>Power Usage</h1>
                        {% for energy_type, graphs in latest_graphs.items() %}
                            {% if graphs.bar_graph_exists and graphs.line_graph_exists %}
                            <div class="row">
                                <div class="col-md-12">
                                    <h2>{{ energy_type|capitalize }} Usage</h2>
                                    <div class="row">
                                        <div class="col-md-5 col-sm-5 col-xs-12 gutter">
                                            <img src="{{ url_for('static', filename='Images/' + graphs.bar_graph_filename) }}" alt="{{ energy_type|capitalize }} Bar Graph" style="width:100%; height:auto;">
                                        </div>
                                        <div class="col-md-7 col-sm-7 col-xs-12 gutter">
                                            <img src="{{ url_for('static', filename='Images/' + graphs.line_graph_filename) }}" alt="{{ energy_type|capitalize }} Line Graph" style="width:100%; height:auto;">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    
                    
                    <!--end of graphs-->
                </div>
            </div>
    
        </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>